name: Ubuntu
on: 
  push:
    paths:
      - 'QtScrcpy/**'
      - '!QtScrcpy/res/**'
      - '.github/workflows/ubuntu.yml'
      - 'ci/linux/**'
  pull_request:
    paths:
      - 'QtScrcpy/**'
      - '!QtScrcpy/res/**'
      - '.github/workflows/ubuntu.yml' 
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        arch: [aarch64]
        target: [aarch64-unknown-linux-gnu]
        os: [ubuntu-20.04] # just for naming package, not running host

        qt-ver: [5.15.2]
        qt-arch-install: [gcc_aarch64]
        gcc-arch: [aarch64]
    env:
      target-name: QtScrcpy
      qt-install-path: ${{ github.workspace }}/${{ matrix.qt-ver }}
      plantform-des: ubuntu
    steps:
      - uses: actions/checkout@v2  

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Install Qt 5.15.2 for AArch64
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: 5.15.2
          arch: aarch64
          dir: /opt/qt
      - name: Install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'
          ssh-key: ${{ secrets.BOT_SSH_KEY }}
      - name: Build RelWithDebInfo
        env:
          ENV_QT_PATH: ${{ env.qt-install-path }}
        run: |
          ci/linux/build_for_linux.sh "RelWithDebInfo"
      - name: Upload RelWithDebInfo
        uses: actions/upload-artifact@v3.1.0
        with:
          name: QtScrcpy-${{ matrix.os }}-${{ matrix.qt-arch-install }}-RelWithDebInfo
          path: output/x64/RelWithDebInfo/*
      - name: Build Release
        env:
          ENV_QT_PATH: ${{ env.qt-install-path }}
        run: |
          ci/linux/build_for_linux.sh "Release"
      - name: Upload Release
        uses: actions/upload-artifact@v3.1.0
        with:
          name: QtScrcpy-${{ matrix.os }}-${{ matrix.qt-arch-install }}-Release
          path: output/x64/Release/*
      - name: Install the zip utility
        run: |
          sudo apt install zip -y
      - name: Zip the Artifacts
        run: |
          zip -r QtScrcpy-${{ matrix.os }}-${{ matrix.qt-arch-install }}.zip output/x64/Release
      - name: Upload to Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file: QtScrcpy-${{ matrix.os }}-${{ matrix.qt-arch-install }}.zip
          asset_name: QtScrcpy-${{ matrix.os }}-${{ matrix.qt-arch-install }}.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
